
---

- hosts: my-test-machine
  tasks: 
  - name: create a directory in /opt folder
    file:
      path: /opt/jar7070
      state: directory
      mode: 0755
      owner: spaneos
      group: spaneos
  - name: create dir
    file:
      path: /opt/
      state: directory
      mode: 0755
      owner: spaneos
      group: spaneos
  - name: send start.sh file fron source to destination
    copy: 
      src: /home/thulasi/start.sh
      dest: /opt/jar9090
      mode: 0755
      owner: spaneos
      group: spaneos
  - name: send stop.sh file from source to destination
    copy: 
      src: /home/thulasi/stop.sh
      dest: /opt/jar9090
      mode: 0755
      owner: spaneos
      group: spaneos
  - name: send service file from source to destination
    copy: 
      src: /home/thulasi/jar8070.service
      dest: /etc/systemd/system
      mode: 0644
  - name: reload the daemon 
    command: systemctl daemon-reload
